package Vista;
import Modelo.*;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
/**
 *
 * @author Valentin
 */
public class VentanaUsuario extends javax.swing.JDialog {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaUsuario.class.getName());

    /** Creates new form VentanaUsuario */
    public VentanaUsuario(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        cmbRango.removeAllItems();
        cmbRango.addItem("ADMIN");
        cmbRango.addItem("EMPLEADO");
        cargarUsuario();
        ImageIcon icono1 = new ImageIcon(getClass().getResource("/Imagenes/imgIconoApp.png"));               
        this.setIconImage(icono1.getImage());
        this.setLocationRelativeTo(null);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cmbUsuarios = new javax.swing.JComboBox<>();
        txtNombre = new javax.swing.JTextField();
        txtContraseña = new javax.swing.JPasswordField();
        cmbRango = new javax.swing.JComboBox<>();
        btnGuardar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("SICPIO - ABM Usuarios");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cmbUsuarios.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cmbUsuarios.setForeground(new java.awt.Color(0, 0, 0));
        cmbUsuarios.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbUsuarios.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cmbUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbUsuariosActionPerformed(evt);
            }
        });
        getContentPane().add(cmbUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 143, 20));

        txtNombre.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtNombre.setForeground(new java.awt.Color(0, 0, 0));
        txtNombre.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 143, -1));

        txtContraseña.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtContraseña.setForeground(new java.awt.Color(0, 0, 0));
        txtContraseña.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtContraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtContraseñaActionPerformed(evt);
            }
        });
        getContentPane().add(txtContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, 143, -1));

        cmbRango.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cmbRango.setForeground(new java.awt.Color(0, 0, 0));
        cmbRango.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbRango.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(cmbRango, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, 143, 20));

        btnGuardar.setText("GUARDAR");
        btnGuardar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        getContentPane().add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 290, 80, 30));

        btnEliminar.setText("ELIMINAR");
        btnEliminar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 290, 80, 30));

        btnVolver.setText("VOLVER");
        btnVolver.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });
        getContentPane().add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, 80, 30));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("ABM USUARIOS");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, -1, 28));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("USUARIO:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, -1, 20));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("NOMBRE:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, -1, 20));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("CONTRASEÑA:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, 20));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("AREA:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, -1, 20));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondoLogin_1.jpg"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 380));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnVolverActionPerformed
    
    private void cargarUsuario(){
        cmbUsuarios.removeAllItems();
        cmbUsuarios.addItem("NUEVO USUARIO");
        for(Usuario u : Logica.Datos.listadoUsuarios){
            cmbUsuarios.addItem(u.getNombreUsuario());
        }
    }
    private void limpiarCamposUsuarios(){
        txtNombre.setText("");
        txtContraseña.setText("");
        cmbRango.setSelectedItem(0);
        txtNombre.requestFocus();
    }
    
    private void cmbUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbUsuariosActionPerformed
        if(cmbUsuarios.getSelectedItem() == null){
            return;
        }
        
        String opcion = cmbUsuarios.getSelectedItem().toString();
        
        if(opcion.equals("NUEVO USUARIO")){
            limpiarCamposUsuarios();
        }else{
            for(Usuario u : Logica.Datos.listadoUsuarios){
                if(u.getNombreUsuario().equals(opcion)){
                    txtNombre.setText(u.getNombreUsuario());
                    txtContraseña.setText(u.getContrasena());
                    cmbRango.setSelectedItem(u.getRango());
                    break;
                }
            }
        }
    }//GEN-LAST:event_cmbUsuariosActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        String nombre = txtNombre.getText().toUpperCase();
        String contra = new String(txtContraseña.getPassword());
        String rango = cmbRango.getSelectedItem().toString();
        
        if(nombre.isEmpty() || contra.isEmpty()){
            JOptionPane.showMessageDialog(this, "INGRESE LOS CAMPOS OBLIGATORIOS");
            return;
        }
        if(!Logica.Validaciones.contrasenaValida(contra)){
            JOptionPane.showMessageDialog(this, "LA CONTRASEÑA NO CUMPLE CON LOS REQUISITOS");
            return;
        }
        boolean existe = false;
        for(Usuario u : Logica.Datos.listadoUsuarios){
            if(u.getNombreUsuario().equals(nombre)){
                u.setContrasena(contra);
                u.setRango(rango);
                existe = true;
                break;
            }
        }
        if(!existe){
            Logica.Datos.listadoUsuarios.add(new Usuario(nombre, contra, rango));
            JOptionPane.showMessageDialog(this, "USUARIO CREADO CON EXITO");
            }
        cargarUsuario();
        limpiarCamposUsuarios();
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        String usuario = txtNombre.getText().toUpperCase();
        if(usuario.equals("NUEVO")){
            JOptionPane.showMessageDialog(this, "SELECCIONE UN USUARIO YA CARGADO");
        }
        if(usuario.equalsIgnoreCase("ADMIN")){
            JOptionPane.showMessageDialog(this, "NO SE PUEDE ELIMINAR EL --ADMIN--");
            return;
        }
        int confirmar = JOptionPane.showConfirmDialog(this, "¿DESEA ELIMINARLO?");
        if(confirmar == JOptionPane.YES_OPTION){
            for(int i = 0; i < Logica.Datos.listadoUsuarios.size(); i++){
                if(Logica.Datos.listadoUsuarios.get(i).getNombreUsuario().equals(usuario)){
                    Logica.Datos.listadoUsuarios.remove(i);
                    JOptionPane.showMessageDialog(this, "USUARIO ELIMINADO");
                    break;
                }
            }
            cargarUsuario();
            limpiarCamposUsuarios();
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void txtContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtContraseñaActionPerformed
        
        String seleccion = cmbUsuarios.getSelectedItem().toString();
        if(seleccion.equals("NUEVO")){
            limpiarCamposUsuarios();
        }else{
            for(Usuario u : Logica.Datos.listadoUsuarios){
                if(u.getNombreUsuario().equals(seleccion)){
                    txtNombre.setText(u.getNombreUsuario());
                    txtContraseña.setText(u.getContrasena());
                    cmbRango.setSelectedItem(u.getRango());
                    break;
                }
            }
        }
    }//GEN-LAST:event_txtContraseñaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                VentanaUsuario dialog = new VentanaUsuario(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnVolver;
    private javax.swing.JComboBox<String> cmbRango;
    private javax.swing.JComboBox<String> cmbUsuarios;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPasswordField txtContraseña;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables

}
