package Vista;
import Modelo.*;
import javax.swing.JOptionPane;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.ImageIcon;
/**
 *
 * @author Valentin
 */
public class Ventas extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Ventas.class.getName());

    /**
     * Creates new form Ventas
     */
    public Ventas() {
        initComponents();
        ImageIcon icono1 = new ImageIcon(getClass().getResource("/Imagenes/imgIconoApp.png"));               
        this.setIconImage(icono1.getImage());
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtBusquedaAceite = new javax.swing.JTextField();
        btnBusqueda = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtCantidad = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btnRealizarVenta = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblStockDisponible = new javax.swing.JLabel();
        txtCliente = new javax.swing.JTextField();
        lblEmpresa = new javax.swing.JLabel();
        btnVolver = new javax.swing.JButton();
        btnHistorial = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SICPIO - Ventas");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtBusquedaAceite.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        txtBusquedaAceite.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtBusquedaAceite.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtBusquedaAceiteKeyPressed(evt);
            }
        });
        getContentPane().add(txtBusquedaAceite, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 140, 390, 28));

        btnBusqueda.setText("BUSCAR");
        btnBusqueda.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnBusqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBusquedaActionPerformed(evt);
            }
        });
        btnBusqueda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnBusquedaKeyPressed(evt);
            }
        });
        getContentPane().add(btnBusqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, 81, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("ACEITE:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(134, 231, -1, -1));

        txtCantidad.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtCantidad.setForeground(new java.awt.Color(0, 0, 0));
        txtCantidad.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtCantidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCantidadKeyPressed(evt);
            }
        });
        getContentPane().add(txtCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(223, 330, 70, 21));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("CANTIDAD:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(112, 330, -1, -1));

        btnRealizarVenta.setText("VENDER");
        btnRealizarVenta.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnRealizarVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRealizarVentaActionPerformed(evt);
            }
        });
        btnRealizarVenta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnRealizarVentaKeyPressed(evt);
            }
        });
        getContentPane().add(btnRealizarVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(315, 390, 107, 27));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("BUSCAR PRODUCTO (ID / NOMBRE)");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, -1, 30));

        lblNombre.setBackground(new java.awt.Color(0, 0, 0));
        lblNombre.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblNombre.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(223, 228, 102, 24));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("DISPONIBLE:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(89, 280, -1, 22));

        lblStockDisponible.setBackground(new java.awt.Color(0, 0, 0));
        lblStockDisponible.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        lblStockDisponible.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(lblStockDisponible, new org.netbeans.lib.awtextra.AbsoluteConstraints(223, 282, 69, 22));

        txtCliente.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        txtCliente.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtClienteActionPerformed(evt);
            }
        });
        txtCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtClienteKeyPressed(evt);
            }
        });
        getContentPane().add(txtCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 60, 390, 30));

        lblEmpresa.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        lblEmpresa.setForeground(new java.awt.Color(0, 0, 0));
        lblEmpresa.setText("CLIENTE / EMPRESA");
        getContentPane().add(lblEmpresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, 196, 30));

        btnVolver.setText("VOLVER");
        btnVolver.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });
        getContentPane().add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 390, 97, 27));

        btnHistorial.setText("HISTORIAL");
        btnHistorial.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnHistorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHistorialActionPerformed(evt);
            }
        });
        getContentPane().add(btnHistorial, new org.netbeans.lib.awtextra.AbsoluteConstraints(192, 390, 111, 27));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondoLogin_1.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-1, 1, 500, 460));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBusquedaActionPerformed
        String busquedaAceite = txtBusquedaAceite.getText().toUpperCase();
        boolean encontrado = false;
        
        for(Producto p : Logica.Datos.listadoLubricantes){
            if(p.getId().equals(busquedaAceite)){
                lblNombre.setText(p.getNombre());
                lblStockDisponible.setText(String.valueOf(p.getStock()));
                encontrado = true;
                break;
            }
        }
        if(!encontrado){
            JOptionPane.showMessageDialog(this, "PRODUCTO INEXSISTENTE EN INVENTARIO");
        }
    }//GEN-LAST:event_btnBusquedaActionPerformed

    private void btnRealizarVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRealizarVentaActionPerformed
        try{
            int cantidad = Integer.parseInt(txtCantidad.getText());
            
            String idEncontrado = txtBusquedaAceite.getText().toUpperCase();
            String nombreCliente = txtCliente.getText().trim().toUpperCase();
            
            boolean clienteCargado = false;
            if(nombreCliente.equals("CF") || nombreCliente.isEmpty()){
                nombreCliente = "CONSUMIDOR FINAL";
                clienteCargado = true;    
            }else{
                for(Cliente c : Logica.Datos.listadoClientes){
                    if(c.getNombre().toUpperCase().equals(nombreCliente)){
                        clienteCargado = true;
                        break;
                    }
                }
            }
            if(!clienteCargado){
                JOptionPane.showMessageDialog(this, "EL CLIENTE NO EXISTE. REGISTRELO O USE CONSUMIDOR FINAL");
                return;
            }
            
            for(Producto p : Logica.Datos.listadoLubricantes){
                if(p.getId().equals(idEncontrado)){
                    if(cantidad > p.getStock()){
                        JOptionPane.showMessageDialog(this, "NO HAY STOCK SUFICIENTE. CANTIDAD DISPONIBLE: " + p.getStock());
                        return;
                    }
                
                    int stockActual = p.getStock();
                    p.setStock(stockActual - cantidad);
                    
                    String fechaActual = new SimpleDateFormat("dd/MM/yyyy HH:mm").format(new Date());
                    Venta nuevaVenta = new Venta(fechaActual, nombreCliente, p.getNombre(), cantidad);
                    Logica.Datos.listadoVentas.add(nuevaVenta);
                    
                    JOptionPane.showMessageDialog(this, "VENTA REALIZADA");
                    limpiarCamposVenta();
                    return;
                }
            }
            JOptionPane.showMessageDialog(this, "PRODUCTO NO ENCONTRADO EN LA LISTA");
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(this, "BUSQUE UN PRODUCTO Y LUEGO INGRESE UNA CANTIDAD VALIDA");
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "ERROR AL REALIZAR LA VENTA: " + e.getMessage());
        }
    }//GEN-LAST:event_btnRealizarVentaActionPerformed

    private void txtCantidadKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCantidadKeyPressed
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
            try{
                btnRealizarVenta.requestFocus();
            }catch(Exception e){
                
            }
        }       
    }//GEN-LAST:event_txtCantidadKeyPressed

    private void txtBusquedaAceiteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBusquedaAceiteKeyPressed
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
            btnBusqueda.requestFocus();
        }
    }//GEN-LAST:event_txtBusquedaAceiteKeyPressed
        
        
    private void btnBusquedaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnBusquedaKeyPressed
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
            btnBusqueda.doClick();
            txtCantidad.requestFocus();    
        }
    }//GEN-LAST:event_btnBusquedaKeyPressed

    private void txtClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtClienteActionPerformed

    private void txtClienteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtClienteKeyPressed
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
            String clienteBusqueda = txtCliente.getText().toUpperCase().trim();
            boolean encontrado = false;
            
            if(clienteBusqueda.isEmpty() || clienteBusqueda.equals("CF") || clienteBusqueda.equals("CONSUMIDOR FINAL")){
                txtCliente.setText("CONSUMIDOR FINAL");
                txtBusquedaAceite.requestFocus();
                return;
            }
            
            for(Cliente c : Logica.Datos.listadoClientes){
                if(c.getNombre() != null && c.getNombre().toUpperCase().contains(clienteBusqueda)){
                    txtCliente.setText(c.getNombre().toUpperCase());
                    encontrado = true;
                    txtBusquedaAceite.requestFocus();
                    break;
                }
            }
            if(!encontrado){
                JOptionPane.showMessageDialog(this, "CLIENTE NO ENCONTRADO");
                txtCliente.selectAll();
            }
        }
    }//GEN-LAST:event_txtClienteKeyPressed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        
        this.dispose();
    }//GEN-LAST:event_btnVolverActionPerformed

    private void btnHistorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHistorialActionPerformed
        VentanaVentas nuevaVenta = new VentanaVentas(this, true);
        nuevaVenta.setVisible(true);
    }//GEN-LAST:event_btnHistorialActionPerformed

    private void btnRealizarVentaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnRealizarVentaKeyPressed
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
        btnRealizarVenta.doClick();
        }   
    }//GEN-LAST:event_btnRealizarVentaKeyPressed
        
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Ventas().setVisible(true));
    }
    
    private void limpiarCamposVenta(){
        txtBusquedaAceite.setText("");
        lblNombre.setText("");
        txtCantidad.setText("");
        txtBusquedaAceite.requestFocus();
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBusqueda;
    private javax.swing.JButton btnHistorial;
    private javax.swing.JButton btnRealizarVenta;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel lblEmpresa;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblStockDisponible;
    private javax.swing.JTextField txtBusquedaAceite;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtCliente;
    // End of variables declaration//GEN-END:variables
}
